<?php

namespace LuckyRomka\LaravelAuth;

use Illuminate\Support\ServiceProvider;

class LaravelAuthServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        $this->loadRoutesFrom(__DIR__.'/routes.php');
        $this->loadViewsFrom(__DIR__.'/Views', 'LaravelAuth');
    }
     public function register()
     {
         //parent::register(); // TODO: Change the autogenerated stub
     }
}
